### ISSUE TITLE
Detail view - First tracker wrongly truncated for udp trackers

### ISSUE THREAD

**Issue by Skee** [PanAeon/transg-tui#1]
If the torrent's first tracker announce URL is a UDP tracker, transg will only show "udp:" as the First Tracker.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/5211/184209771-eb372e00-0d89-4855-a96f-1efd6509ff64.png">

In this case, the tracker URL is "udp://tracker.coppersurfer.tk:6969".

**Comment by PanAeon** [comment]
should be fixed in the recent build.

**Comment by Skee** [comment]
Looking good!
