### ISSUE TITLE
Some parts of `transg-tui` are barely visible on light terminals

### ISSUE THREAD

**Issue by zeerooth** [PanAeon/transg-tui#4]
Examples:
![1661720607](https://user-images.githubusercontent.com/27929520/187094521-056ef8b1-7d61-421b-92aa-a7d7b9f09be5.png)
![1661720652](https://user-images.githubusercontent.com/27929520/187094527-2a9f89e8-2009-4241-98d8-36a671ded6aa.png)

It's especially hard to read on lower brightness settings. I think the main reason for that are the hardcoded colours, for example [here](https://github.com/PanAeon/transg-tui/blob/2930f0e60958991e25cf7d8fb09fef1f0ff91e4f/src/ui.rs#L70). I think removing them might partially fix the issue as terminals should determine default colour themselves or use a crate like https://github.com/Canop/terminal-light to detect the style.

**Comment by PanAeon** [comment]
Thanks for mentioning `terminal-light`! I've added color detection and some color customization options. This is default white look now:
![swappy-20220830-115653](https://user-images.githubusercontent.com/686076/187395385-f0468a1d-02a2-49b9-9269-2c7444aaead5.png)

**Comment by zeerooth** [comment]
Yup, same thing for me - everything looks great now, thanks for taking care of that!
